kkategorilerr = {
    "technology": ["coding", "programming", "innovation", "robotics", "gadgets", "software", "development", "machinelearning", "cybersecurity", "automation"],
    "travel": ["adventure", "explore", "vacation", "wanderlust", "destination", "journey", "tourism", "backpacking", "itinerary", "exploration"],
    "food": ["delicious", "foodie", "recipes", "cooking", "tasty", "cuisine", "gastronomy", "culinary", "spices", "homemade"],
    "fitness": ["exercise", "workout", "healthy", "wellness", "strength", "cardio", "training", "nutrition", "flexibility", "endurance"],
    "music": ["musician", "concert", "playlist", "melody", "harmony", "instrument", "composition", "lyrics", "genre", "orchestra"],
    "nature": ["outdoors", "wildlife", "scenic", "landscape", "environment", "ecosystem", "conservation", "biodiversity", "habitat", "wilderness"],
    "art": ["creative", "painting", "sculpture", "gallery", "design", "visualarts", "abstract", "impressionism", "expressionism", "craftsmanship"],
    "photography": ["photooftheday", "capture", "snapshot", "composition", "exposure", "portrait", "landscapephotography", "blackandwhite", "aesthetic", "photoshoot"],
    "fashion": ["style", "trendy", "couture", "wardrobe", "accessories", "fashionista", "designer", "streetstyle", "vintage", "runway"],
    "books": ["literature", "novel", "readinglist", "bookworm", "bestseller", "author", "fiction", "nonfiction", "literary", "classic"],
    "movies": ["cinema", "filmography", "actor", "director", "screenplay", "hollywood", "documentary", "blockbuster", "indiefilm", "cinematography"],
    "sports": ["athletics", "competition", "teamspirit", "champion", "fitness", "athlete", "sportsmanship", "gameon", "training", "victory"],
    "science": ["discovery", "research", "experiment", "technology", "innovation", "scientist", "scientificmethod", "hypothesis", "labresearch", "dataanalysis"],
    "history": ["historical", "past", "ancient", "civilization", "archaeology", "historian", "heritage", "medieval", "renaissance", "historybooks"],
    "politics": ["government", "democracy", "policy", "leadership", "citizenship", "politicalscience", "governance", "ideology", "voting", "publicpolicy"],
    "health": ["wellness", "nutrition", "exercise", "mindfulness", "selfcare", "mentalhealth", "wellbeing", "holistic", "fitnessjourney", "healthylifestyle"],
    "business": ["entrepreneurship", "startup", "leadership", "innovation", "economy", "businessstrategy", "corporate", "marketing", "finance", "entrepreneurmindset"],
    "education": ["learning", "knowledge", "students", "teacher", "classroom", "educational", "academic", "schooling", "edtech", "pedagogy"],
    "gaming": ["videogames", "gamerlife", "gamingcommunity", "esports", "console", "gamedevelopment", "gamingsetup", "gamergirl", "streaming", "virtualreality"],
    "pets": ["petlovers", "animalcare", "companionship", "petadoption", "pawprint", "doglovers", "catsofinstagram", "petfriendly", "furryfriend", "veterinary"],
    "gardening": ["greenthumb", "gardendesign", "horticulture", "outdoors", "plants", "gardeningtips", "landscapegardening", "botanical", "soilhealth", "permaculture"],
    "architecture": ["design", "urbanplanning", "architecturalstyle", "buildingdesign", "construction", "architect", "skyscraper", "interiordesign", "sustainablearchitecture", "landscapedesign"],
    "travelphotography": ["wanderlust", "explore", "beautifuldestinations", "travelgram", "passportready", "phototravel", "travelblogger", "traveldiaries", "adventureawaits", "globetrotter"],
    "cooking": ["homemade", "culinary", "foodphotography", "cheflife", "deliciousness", "foodbloggers", "foodporn", "foodgasm", "foodlove", "foodart"],
    "crafts": ["diy", "handmade", "creativity", "craftsmanship", "artistic", "crafting", "diycrafts", "handcrafted", "artisan", "craftersofinstagram"],
    "technologynews": ["innovation", "techindustry", "futuretech", "digital", "techupdates", "technologysolutions", "techtrends", "gadgets", "researchanddevelopment", "cuttingedgetech"],
    "celebrities": ["stardom", "redcarpet", "celebritylife", "fame", "hollywood", "celebritynews", "celebritystyle", "paparazzi", "starstruck", "moviepremiere"],
    "cars": ["automotive", "carlovers", "supercars", "driving", "roadtrip", "carculture", "luxurycars", "vintagecars", "carphotography", "automechanic"],
    "beauty": ["makeup", "skincare", "fashion", "cosmetics", "glamour", "beautybloggers", "makeupaddict", "beautyqueen", "styleinspo", "naturalbeauty"],
}

